//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMAS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIMASDbContext : DbContext
    {
        public CIMASDbContext()
            : base("name=CIMASDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AwardPunishmentIfo> AwardPunishmentIfoes { get; set; }
        public DbSet<CourseTimeIfo> CourseTimeIfoes { get; set; }
        public DbSet<DepartmentIfo> DepartmentIfoes { get; set; }
        public DbSet<DictActivity> DictActivities { get; set; }
        public DbSet<DictCoursePlace> DictCoursePlaces { get; set; }
        public DbSet<DictFamilyOrigin> DictFamilyOrigins { get; set; }
        public DbSet<DictNation> DictNations { get; set; }
        public DbSet<DictPoliticsStatu> DictPoliticsStatus { get; set; }
        public DbSet<DictPosition> DictPositions { get; set; }
        public DbSet<DictProfClass> DictProfClasses { get; set; }
        public DbSet<DictProfName> DictProfNames { get; set; }
        public DbSet<DictRegister> DictRegisters { get; set; }
        public DbSet<DictRelation> DictRelations { get; set; }
        public DbSet<DictSemester> DictSemesters { get; set; }
        public DbSet<DictStudentSource> DictStudentSources { get; set; }
        public DbSet<DictTerm> DictTerms { get; set; }
        public DbSet<HeightWeightIfo> HeightWeightIfoes { get; set; }
        public DbSet<ImportantActivitiesIfo> ImportantActivitiesIfoes { get; set; }
        public DbSet<InjureisIfo> InjureisIfoes { get; set; }
        public DbSet<OptionalCourseIfo> OptionalCourseIfoes { get; set; }
        public DbSet<RequiredCourseIfo> RequiredCourseIfoes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SocietyRelationIfo> SocietyRelationIfoes { get; set; }
        public DbSet<StuBasicIfo> StuBasicIfoes { get; set; }
        public DbSet<StuGradeIfo> StuGradeIfoes { get; set; }
        public DbSet<StuScheduleIfo> StuScheduleIfoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TrainingTestIfo> TrainingTestIfoes { get; set; }
        public DbSet<TrainTestTimeRankIfo> TrainTestTimeRankIfoes { get; set; }
        public DbSet<UnionHonorIfo> UnionHonorIfoes { get; set; }
    }
}
