//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMAS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentIfo
    {
        public int ID { get; set; }
        public Nullable<int> DictSemesterID { get; set; }
        public string StuId { get; set; }
        public string Company { get; set; }
        public string Platoon { get; set; }
        public string Squad { get; set; }
        public Nullable<int> DictPositionID { get; set; }
    
        public virtual DictPosition DictPosition { get; set; }
        public virtual DictSemester DictSemester { get; set; }
    }
}
