//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMAS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictPoliticsStatu
    {
        public DictPoliticsStatu()
        {
            this.SocietyRelationIfoes = new HashSet<SocietyRelationIfo>();
            this.StuBasicIfoes = new HashSet<StuBasicIfo>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<SocietyRelationIfo> SocietyRelationIfoes { get; set; }
        public virtual ICollection<StuBasicIfo> StuBasicIfoes { get; set; }
    }
}
