//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMAS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictProfClass
    {
        public DictProfClass()
        {
            this.RequiredCourseIfoes = new HashSet<RequiredCourseIfo>();
            this.StuBasicIfoes = new HashSet<StuBasicIfo>();
        }
    
        public int ID { get; set; }
        public string EntranceYear { get; set; }
        public Nullable<int> DictProfNameID { get; set; }
        public string ClassCode { get; set; }
    
        public virtual DictProfName DictProfName { get; set; }
        public virtual ICollection<RequiredCourseIfo> RequiredCourseIfoes { get; set; }
        public virtual ICollection<StuBasicIfo> StuBasicIfoes { get; set; }
    }
}
