//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMAS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InjureisIfo
    {
        public int ID { get; set; }
        public string StuID { get; set; }
        public string Position { get; set; }
        public System.DateTime InjuresTime { get; set; }
        public string RecoverOrNot { get; set; }
        public string Details { get; set; }
        public string RecoverTime { get; set; }
    }
}
