//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMAS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalCourseIfo
    {
        public OptionalCourseIfo()
        {
            this.StuScheduleIfoes = new HashSet<StuScheduleIfo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DictSemesterID { get; set; }
        public Nullable<int> CourseTimeID { get; set; }
        public Nullable<int> DictPlaceID { get; set; }
        public string Weeks { get; set; }
        public Nullable<int> DictProfClassID { get; set; }
    
        public virtual DictCoursePlace DictCoursePlace { get; set; }
        public virtual DictSemester DictSemester { get; set; }
        public virtual ICollection<StuScheduleIfo> StuScheduleIfoes { get; set; }
    }
}
