//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMAS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuBasicIfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string StuCode { get; set; }
        public Nullable<int> DictProfClassID { get; set; }
        public Nullable<int> DictNationID { get; set; }
        public string BirthPlace { get; set; }
        public string IDCardNumber { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> DictRegisterID { get; set; }
        public Nullable<int> DictStuSourceID { get; set; }
        public Nullable<int> DictPoliticsStatusID { get; set; }
        public string TelephoneNum { get; set; }
        public string QQNum { get; set; }
        public string Specialty { get; set; }
        public string PersonalExperience { get; set; }
        public Nullable<bool> SingleChild { get; set; }
        public Nullable<bool> SingleParent { get; set; }
        public Nullable<int> DictFamilyOriginID { get; set; }
        public string FamilyAddress { get; set; }
        public string ZIPCode { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual DictFamilyOrigin DictFamilyOrigin { get; set; }
        public virtual DictNation DictNation { get; set; }
        public virtual DictPoliticsStatu DictPoliticsStatu { get; set; }
        public virtual DictProfClass DictProfClass { get; set; }
        public virtual DictRegister DictRegister { get; set; }
        public virtual DictStudentSource DictStudentSource { get; set; }
    }
}
