//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMAS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTestIfo
    {
        public int ID { get; set; }
        public string StuID { get; set; }
        public int TimeRankID { get; set; }
        public Nullable<int> DictTerm { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual DictTerm DictTerm1 { get; set; }
        public virtual TrainTestTimeRankIfo TrainTestTimeRankIfo { get; set; }
    }
}
